apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      - container: vivekmanne/ultimate-cicd-pipeline
  labels:
    app: spring-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: vivekmanne/ultimate-cicd-pipeline:10
        ports:
        - containerPort: 8080
